# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ">=1.23.0"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...


# https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63
    - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o pom_to_markdown_${{ github.ref_name }}_darwin_amd64 .
    - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o pom_to_markdown_${{ github.ref_name }}_darwin_arm64 .
    - run: CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o pom_to_markdown_${{ github.ref_name }}_linux_386 .
    - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o pom_to_markdown_${{ github.ref_name }}_linux_amd64 .
    - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o pom_to_markdown_${{ github.ref_name }}_linux_arm64 .

     # create checksums.txt
    - run: shasum -a 256 pom_to_markdown_* > checksums.txt

    - name: Create a Release in a GitHub Action
      uses: softprops/action-gh-release@v2
      with:
        files: |
          pom_to_markdown_${{ github.ref_name }}_darwin_amd64
          pom_to_markdown_${{ github.ref_name }}_darwin_arm64
          pom_to_markdown_${{ github.ref_name }}_linux_386
          pom_to_markdown_${{ github.ref_name }}_linux_amd64
          pom_to_markdown_${{ github.ref_name }}_linux_arm64
          checksums.txt
